### ISSUE TITLE
Jackett outdated

### ISSUE THREAD

**Issue by boced66** [onedr0p/containers#130]
Hello, 
Jackett has not been updated for 2 months, the current version is v0.20.2660 while the version here is v0.20.2297
https://hub.docker.com/r/linuxserver/jackett

Can you update ?
Thanks

**Comment by onedr0p** [comment]
Hi @boced66 I have stopped maintaining a jackett container in favor of using Prowlarr. Unlike binhex, linuxserverio or hotio I don't strive to support every application out there, only the ones I find useful.

Maybe consider using Prowlarr as an alternative?

I created an issue and had no one raise up and question it since. See https://github.com/onedr0p/containers/issues/106
