### ISSUE TITLE
Sonar 4.x has issues with DNS resolving

### ISSUE THREAD

**Issue by EugenMayer** [onedr0p/containers#942]
# Env:
 - k3s (1.28.4) k8s cluster
 - running the truenas chart for sonar (19.0.25)
 - running sonarr 4.0.78

# Issue
With this setup, sonar can only resolve public domains and ('most probably) does not use the DNS in my k8s / ubuntu node (which is my private DNS). Resolving any private domains of my DNS server (opnsense/unbound) does not work within sonarr. It most probably uses one of the 1.1.1.1/2.2.2.2/8.8.8.8 sorts instead (or it is just an other alpine DNS bug).

Entering the sonarr pod/container and running `nslookup downloader.mydomain.tld` does work without any issues though.

I tried 2 different service (plex / downloader) which both run on my k8s host - both fail for the same reason (lookup failed)

I'am running the above setup docker based (linuxserver/sonarr) for several years now, but was runngint 3.x.

# What i tried to fix it

Running using the same chart 19.0.25 but with `ghcr.io/onedr0p/sonarr:3.0.10` does work without any issues.

# Thoughts

I would usually not open an issue with the one containerizing the application, since the above sound like a .NET/application issue - but you based your container on alpine which notoriously has several DNS issues ( like https://bell-sw.com/blog/how-to-deal-with-alpine-dns-issues/ ). And seeing that 3.0.10 was debian/bookworm based, this could be very much the actual issue - alpine alone.

Also i skimmed through the DNS issues on https://github.com/Sonarr/Sonarr/issues and there is nothing there yet - so it really could go down due to the OS

What are your thoughts here? Any other reports of DNS issues with 4.x already in?

**Comment by EugenMayer** [comment]
I doubt i will go down the alpine DNS rabbit whole. Usually i'am as curious as you seem here - but honestly, not with alpine. The existence of musl and what it causes should have never been happened and it cause so many issues for me already (i'am really doing this docker thing for quiet a while .. ) it's not worth it.

I most probably will simply either use an alternative chart, or create my own chart or see if i can make the truenas chart working with linuxserver/sonar - or i will fork your image and base it on debian again.

All of those options are better then dealing with alpine and DNS issues.

> With that said I've heard of a couple accounts of strange issues in that the arrs are unable to reach cluster dns for postgres during start, however when using the postgres svc IP it works. The really strange piece is that for sab and qb which are also deployed in the cluster work just fine within the arrs with cluster DNS. It's really confusing.

This could be rather an issue with https://github.com/EugenMayer/helm-charts/tree/main/charts/coredns-private-dns-fix and the randomness comes from coredns picking a public/private dns for each other request.

Using an SVC of course fixes it, since it uses no upstream at all, it will be resovled without leaving coredns - but that is not an option here. Going directly to the service will skip ssl-offloading via my LB.

> I'm interested if you're able to test out hotio or lsio images in your cluster and report back. Those are also Alpine and should have the same issue.

I'am a big fan of linuxserver and would rather opt in for that then trying anything else with alpine - sorry.

Usually i'am really interested in contributing and solving issues like these - but alpine with musl is a nogo for me. I has eaten my time so much and there are way to many alternatives.

**Comment by onedr0p** [comment]
As mentioned [LinuxServer also uses Alpine](https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile#L3) for their base for the Arrs which is why I'm curious if you can reproduce this issue on their container. I suspect you will likely run into the same issue.

This repo is set up mostly to be fork friendly, so if you want to do that and build the containers with Ubuntu that should resolve your issue.

**Comment by EugenMayer** [comment]
Kind of curious behind your rational for

>  I'm sure that if this container was moved back to Ubuntu your problems would go away though, however it's unlikely for that to happen due to the added maintenance cost of this repo.

I understand, you might rebuild on alpine base image via CI and you lean towards apk thus installing packages and maybe shared shims (not seen those yet, you  use plain Dockerfile's, no templates).

Why i ask, docker was made for the exact reason of not forcing every application on the same OS, rather on the OS it fits best.

Do not get me wrong, it is your choice and i respect that, just interested about your POV

**Comment by onedr0p** [comment]
Alpine was chosen due to consistency, lessen the maintenance burden and having one path forward for containers to use as a base. Packages in the Alpine repos are more up-to-date than anything in the the Ubuntu/Debian repositories which means less apt add repo shenanigans.

As it stands, Plex is the only container that _needs_ Ubuntu in my repo and even that can be made into an [Alpine container](https://github.com/spritsail/plex-media-server) if I fought hard enough building it that way. Plex will likely be unchanged though, or at least the base image for Ubuntu might get absorbed into the Plex Dockerfile as I have no need for building Ubuntu base image anymore.

I understand having MUSL based images can bring issues with DNS, I've been fighting it since 2016. However it looks like the team behind MUSL has finally [agreed on TCP fallback to the DNS stub resolver](https://www.openwall.com/lists/musl/2023/05/02/1), so we might see more support in the future and be rid of the pesky DNS issues once and for all.

**Comment by onedr0p** [comment]
@EugenMayer looks like @funkypenguin builds sonarr and maybe others with Ubuntu

https://github.com/geek-cookbook/containers

**Comment by EugenMayer** [comment]
@onedr0p thanks for the heads up.

**Comment by funkypenguin** [comment]
It's always DNS 🤦🏻 

One sneaky issue which bit me with alpine (IDK if it's your issue), is that I was applying a DNS search domain (`elfhosted.com`) to my nodes as part of the standard OS install. There's a wildcard on that domain (`*.elfhosted.com`), and so my alpine pods would try resolving every hostname against that wildcard (`google.com.elfhosted.com`).

[This issue](https://github.com/kubernetes/kubernetes/issues/64924) gives some insight, but the conclusive solution in my case was to use a different search domain for my nodes' OS, one which did **not** have a wildcard record!

**Comment by EugenMayer** [comment]
That is not my issue, public DNS records work, private do not work. I have a search domain yes.
